myapp/urls.py
from django.urls import path
from . import views


urlpatterns = [

    path('', views.get_site_sections, name = 'index'),
    path('appointment_done/', views.success_appointment, name = 'success_appointment'),  
    path('cert_results/', views.certification_results, name = 'cert_results'),
    path('team/', views.get_team, name = 'team'),
    path('info/', views.get_info, name = 'info'),
    path('quiz/', views.quiz, name = 'quiz'),
    # path('quiz_start_page/', views.quiz_start_page, name = 'quiz_start_page'),
    path('info/<slug:info_slug>/', views.get_info_details, name = 'info_detailes'),
    path('<slug:part_slug>/', views.get_technician_content, name = 'section'),
    path('area/<slug:part_slug>/', views.get_education_part, name = 'part'),                  
    path('edu_program/<slug:content_slug>/', views.get_training_content, name = 'content'),   
    path('edu_content/<slug:fin_content_slug>/', views.get_content_to_study, name = 'study'),
    path('certification_appointment/<slug:app_id>/', views.make_cert_appointment, name = 'cert_appointment'),  
    path('training_appointment/<slug:app_id>/', views.make_training_appointment, name = 'training_appointment'),
    path('online_certification/<slug:cert_area>/', views.quiz, name = 'quiz')



    
    

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('users/', include('users.urls', namespace="users")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordChangeView


app_name = "users"

urlpatterns = [

    path('login/', views.LoginUser.as_view(), name = 'login'),
    path('logout/', views.logout_user, name = 'logout'), 
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password_change/<int:pk>/', views.UserPasswordChange.as_view(), name='password_change'),
    # path('password_change/<int:pk>/', views.change_password, name='password_change'),
    path('password-change/done', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('profile/<int:pk>/', views.ProfileUser.as_view(), name='profile'),
    path('profile_search/', views.profile_search, name='profile_search'),

]

myapp/forms.py
from django import forms
from .models import Certification_appointment,Dealers,Edu_programs,Training_shedule, Training_participants, QuesModel
import datetime as dt


HOUR_CHOICES = [(dt.time(hour=x), '{:02d}:00'.format(x)) for x in range(0, 24)]                     ##варианты выбора времени



class CertificationAppointmentForm(forms.ModelForm):

    # dlr = forms.CharField(label='Название дилерского центра', max_length=100)
    # employee_id = forms.CharField(label='ID сотрудника', max_length=100)
    # employee_name = forms.CharField(label='Имя сотрудника', max_length=100)
    # employee_last_name = forms.CharField(label='Фамилия сотрудника', max_length=100)
    # category = forms.ModelChoiceField(label='Выберите категорию', queryset=Category.objects.all())        ## Оставил как пример списка | empty_label

    dlr = forms.ModelChoiceField(queryset=Dealers.objects.all(), empty_label='Дилер не выбран', label='Дилерский центр')
    employee_id = forms.CharField(label='ID сотрудника', max_length=100)
    level = forms.ModelChoiceField(queryset=Edu_programs.objects.all(),empty_label='Уровень не выбран', label='Уровень сертификации')
    class Meta:
        model = Certification_appointment
        # fields = ['job_title', 'certification_date', 'certification_time', 'dlr', 'employee_id', 'employee_name', 'employee_last_name']
        fields = ['dlr', 'employee_id', 'employee_name', 'employee_last_name', 'level']
        labels = {'employee_id': 'ID сотрудника',
                  'employee_name': 'Имя сотрудника',
                  'employee_last_name':'Фамилия сотрудника'
                  }
        # widgets = {'certification_time': forms.Select(choices=HOUR_CHOICES)}            ##Выбор часов в форме


    #     job_title = models.CharField(max_length=250)
    # certification_date = models.DateField()
    # certification_time = models.TimeField()
    # created_at = models.DateTimeField(auto_now_add=True)
    # # slug = models.SlugField(max_length=255, unique=True, db_index=True)
    # is_published = models.BooleanField(default=0)
    # dlr=models.CharField(max_length=250,null=True)
    # employee_id = models.CharField(max_length=250, null=True)
    # employee_name = models.CharField(max_length=250, null=True)
    # employee_last_name = models.CharField(max_length=250, null=True)
    # is_available = models.BooleanField(default=1)


class TrainingAppointmentForm(forms.ModelForm):

    # dlr = forms.CharField(label='Название дилерского центра', max_length=100)
    # employee_id = forms.CharField(label='ID сотрудника', max_length=100)
    # employee_name = forms.CharField(label='Имя сотрудника', max_length=100)
    # employee_last_name = forms.CharField(label='Фамилия сотрудника', max_length=100)
    # category = forms.ModelChoiceField(label='Выберите категорию', queryset=Category.objects.all())        ## Оставил как пример списка | empty_label

    dlr = forms.ModelChoiceField(queryset=Dealers.objects.all(), empty_label='Дилер не выбран', label='Дилерский центр')
    class Meta:
        model = Training_participants
        # fields = ['job_title', 'certification_date', 'certification_time', 'dlr', 'employee_id', 'employee_name', 'employee_last_name']
        fields = ['dlr', 'employee_id', 'employee_name', 'employee_last_name']
        labels = {'employee_id': 'ID сотрудника',
                  'employee_name': 'Имя сотрудника',
                  'employee_last_name':'Фамилия сотрудника'
                  }


class QuizForm(forms.ModelForm):

    question = forms.CharField (label="Вопрос")
    op1 = forms.CharField (label="Ответ 1")
    op2 = forms.CharField (label="Ответ 2")
    op3 = forms.CharField (label="Ответ 3")
    op4 = forms.CharField (label="Ответ 4")
    answer = forms.CharField


    # dlr = forms.CharField(label='Название дилерского центра', max_length=100)
    # employee_id = forms.CharField(label='ID сотрудника', max_length=100)
    # employee_name = forms.CharField(label='Имя сотрудника', max_length=100)
    # employee_last_name = forms.CharField(label='Фамилия сотрудника', max_length=100)
    # category = forms.ModelChoiceField(label='Выберите категорию', queryset=Category.objects.all())        ## Оставил как пример списка | empty_label

    # dlr = forms.ModelChoiceField(queryset=Dealers.objects.all(), empty_label='Дилер не выбран', label='Дилерский центр')
    class Meta:
        model = QuesModel
        # fields = ['job_title', 'certification_date', 'certification_time', 'dlr', 'employee_id', 'employee_name', 'employee_last_name']
        fields = ['question','op1', 'op2', 'op3', 'op4', 'answer']
        # labels = {'employee_id': 'ID сотрудника',
        #           'employee_name': 'Имя сотрудника',
        #           'employee_last_name':'Фамилия сотрудника'
        #           }

myapp/views.py
import random
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from myapp.forms import CertificationAppointmentForm,TrainingAppointmentForm
from .models import Video, Site_sections, Technicians_cources, Videos, Training_parts, Training_chapters, Certification_appointment, Training_shedule, Training_participants, Content, Edu_Results, Cert_Results, Info, QuesModel, QuesModel, Edu_programs
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import render, get_object_or_404
from .services import open_file
from django.http import FileResponse, Http404
from django.contrib import messages
from django.db.models import Count
from users.models import User

# Create your views here.

def test (request):
    return render(request, 'myapp/test.html')

def get_list_video(request):
    return render (request, 'myapp/home.html', {'video_list': Video.objects.all()})


def get_video(request,pk: int):
    _video =get_object_or_404(Video, id=pk)
    return render (request, 'myapp/video.html', {'video': _video})
                   

def get_streaming_video(request, pk: int):
    file, status_code, content_length, content_range = open_file(request, pk)
    response = StreamingHttpResponse(file, status=status_code, content_type='video/mp4')

    response['Accept-Ranges'] = 'bytes'
    response['Content-Length'] = str(content_length)
    response['Cache-Control'] = 'no-cache'
    response['Content-Range'] = content_range
    return response

def entry_page(request):
    return render(request, 'myapp/entrypage.html')




def service_advisors_content(request):
    return render(request, 'myapp/sacontent.html')


def pdf_view(request):
    with open('test.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'filename=some_file.pdf'
        return response
    


@login_required
def get_site_sections(request):
    sections = Site_sections.objects.all()

    data = {
        'sections': sections,

    }

    return render(request, 'myapp/index.html', data)

@login_required
def get_technician_content(request, part_slug):             ## переименовать метод т.к. он не только для механиков

    cources = Technicians_cources.objects.all()
    slug_area = get_object_or_404(Site_sections, slug=part_slug)
    certifications= Certification_appointment.objects.all()
    trainings = Training_shedule.objects.all()
    online_certifications = Edu_programs.objects.all()
    edu_results = Edu_Results.objects.filter(username=request.user)
    cert_results = Cert_Results.objects.filter(user_id=request.user)  

    participants = Training_participants.objects.values('training_id').annotate(the_count=Count('training_id'))

    print (cert_results)
    data = {
        'cources': cources,
        'slug_area': slug_area,
        'certifications': certifications,
        "trainings": trainings,
        "participants": participants,
        'online_certifications': online_certifications,
        'edu_results': edu_results,
        'cert_results': cert_results      

    }

    return render(request, 'myapp/techcont.html', data)


@login_required
def get_education_part(request, part_slug):
    parts = Training_parts.objects.all()
    cources = get_object_or_404(Technicians_cources, slug=part_slug)
    data = {
        'parts': parts,
        'cources': cources,
    }
    print(parts)
    print(cources)


    return render(request, 'myapp/eduparts.html', data)


@login_required
def get_training_content(request, content_slug):

    parts = Training_chapters.objects.all()
    cources = get_object_or_404(Training_parts, slug=content_slug)
    contents = Content.objects.all()
    edu_results_list = Edu_Results.objects.filter(username=request.user)


    data = {
        'parts': parts,
        'cources': cources,
        'contents': contents,                   # Не понятно зачем это тут
        'edu_results_list': edu_results_list
    }

    print(cources)
    return render(request, 'myapp/educontent.html', data)



@login_required
def get_content_to_study(request, fin_content_slug):

    parts = Training_chapters.objects.all()
    cources = get_object_or_404(Training_chapters, slug=fin_content_slug)

    contents = Content.objects.all()
    try:
        edu_results_list = Edu_Results.objects.filter(username=request.user).get(title=fin_content_slug)
    except:
        edu_results_list = Edu_Results.objects.create(
            username = request.user.username,
            title = fin_content_slug,
            )
        edu_results_list.save()
        print('запись добавлена')
    edu_results_list = Edu_Results.objects.filter(username=request.user)
    data = {
        'cources': cources,
        'contents': contents,
        'parts': parts,
        'edu_results_list': edu_results_list
    }
    return render(request, 'myapp/content.html', data)






def get_tt_level_content(request):
    return render(request, 'myapp/tt_level.html', {'cources': Technicians_cources.objects.all(), 'videos':Videos.objects.all()})


@login_required
def make_cert_appointment(request,app_id):
    appointment = Certification_appointment.objects.get(pk=app_id)
    if request.method == 'POST':
        form = CertificationAppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            appointment.save()
            appointment.is_available = False
            appointment.save()
            messages.success(request, 'some text')

    else:
        form = CertificationAppointmentForm()


    data = {
        'form': form,

    }

    return render(request, 'myapp/certappform.html', data)

@login_required
def make_training_appointment(request,app_id):
    appointment = Training_shedule.objects.get(pk=app_id)
    print(appointment.training_id)
    print(app_id)

    training_id = appointment.training_id
    training_name = appointment.training_name
    training_start_date = appointment.training_start_date
    training_end_date = appointment.training_end_date

    max_participants = appointment.max_participants
    is_published = appointment.is_published
    is_available = appointment.is_available
    print(training_start_date)
    temp = Training_participants(training_id = appointment.training_id, training_name = appointment.training_name, training_start_date = appointment.training_start_date, training_end_date = appointment.training_end_date)

    if request.method == 'POST':
        form = TrainingAppointmentForm(request.POST, instance=appointment)
        if form.is_valid():
            temp.dlr=form.cleaned_data['dlr']
            temp.employee_id = form.cleaned_data['employee_id']
            temp.employee_name = form.cleaned_data['employee_name']
            temp.employee_last_name = form.cleaned_data['employee_last_name']

            temp.save()

            return redirect ('success_appointment')
    else:
        form = TrainingAppointmentForm()

    data = {
        'form': form,
    }

    return render(request, 'myapp/trainingappform.html', data)


def test_pdf(request):

    temp = Content.objects.all()

    data = {
            'temp': temp
        }
    return render(request, 'myapp/test.html', data)

@login_required
def success_appointment(request):
    return render(request, 'myapp/success_appointment.html')

@login_required
def certification_results(request):
    profile = User.objects.get(username=request.user)
    cert_results = Cert_Results.objects.all()
    data = {
            'cert_results': cert_results,
            'profile': profile
        }

    return render(request, 'myapp/certification_results.html', data)



@login_required
def get_team(request):
    profile = User.objects.get(username=request.user)
    dlr = profile.dlr
    teams = User.objects.filter(dlr=dlr).order_by('last_name')
    print(dlr)
    cert_results = Cert_Results.objects.all()
    
    data = {
            'teams': teams,
            'profile': profile,
            'cert_results': cert_results
        }

    return render(request, 'myapp/team.html', data)


@login_required
def get_info(request):
    info = Info.objects.all()
    data = {
            'info': info,

        }

    return render(request, 'myapp/info.html', data)

@login_required
def get_info_details (request, info_slug):
    concreate_news = Info.objects.filter(slug=info_slug)
    print(concreate_news)
    data = {
        'info': concreate_news,

    }
    return render(request, 'myapp/info_details.html', data)



@login_required
def quiz_start_page(request):
    quantity_of_question = 1 # Тут жестко задаем количество вопросов в тесте
    full_quiz_list =[]
    final_quiz_list = []
    answer_list = []
    quiz = QuesModel.objects.all().values()


    for i in quiz:
        full_quiz_list.append(i)
    # print(full_quiz_list)
    
    for i in range(0, quantity_of_question):               
        question_id = full_quiz_list[random.randint(0, len(full_quiz_list)-1)]
        final_quiz_list.append(question_id)
        full_quiz_list.remove(question_id)

    print('final_quiz_list')
    print(final_quiz_list)


    data = {
        'quiz': final_quiz_list,
        'answer_list': answer_list
    }
    return render(request, 'myapp/quiz_start_page.html', data)




@login_required
def quiz(request, cert_area):
    print(cert_area)
    print ('-'* 200)
    quantity_of_question = 3 # Тут жестко задаем количество вопросов в тесте
    full_quiz_list =[]
    # final_quiz_list = []
    answer_list = []
    # quiz = QuesModel.objects.all().values()
    quiz = QuesModel.objects.filter(cert_area_test = cert_area).values()

myapp/templates/myapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Academy Toyota{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/myapp/css/style.css' %}">
</head>
<body>
    <div class="container">
        {% include "myapp/navbar.html" %}
        {% block content %}
        <p>Something will appear soon...</p>
        {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

myapp/templates/myapp/certappform.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->



{% block content %}


<h1 class="test"> {{ cources.title }}</h1>
{% include "myapp/messages.html" %}

<form action="" method="post">
    {% csrf_token %}
    
    <table class="table-form">
        
        {{ form.as_table }}
        </table>
    <p><button type="submit" class="btn btn-primary">Зарегистрировать</button></p>
</form>

{% endblock content %}

myapp/templates/myapp/certification_results.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>Ниже указаны ваши сертификаты:</h1>





    {% for cert in cert_results %}
        {% if profile.username == cert.user_id and cert.status == 'OK' and cert.cert_status == 'Active' %}
        <div class="certification-line">
            <div>
                <h5>Программа обучения: {{cert.cerification_name}}</h5> 

            </div>
                <h5>
                    Дата сертификации: {{cert.create_at}} 

                </h5>
        </div>
       
        {% endif %}
    {% endfor%}

{% endblock %}

myapp/templates/myapp/content.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->
{% load embed_video_tags %}

{% block content %}

<h1 class="page-name"> {{ cources.title }}</h1>


<div class="page-area">
    <div class="left-sidebar">

            {% for part in parts %}
                {% if cources.program_name == part.program_name and part.is_published %}
                    <div class="list-content">
                        <h5>
                            <a class="list-group-item" href="{% url 'study' part.slug %}">{{ part.chapter_name }}</a>
                        </h5>
                    {% for edu_results in edu_results_list %}
                        {% if edu_results.title == part.slug and edu_results.username == request.user.username%}
                            <h5 class="status-done">Изучено</h5>
                        {% endif %}
                    {% endfor %}
            </div>
                {% endif %}
            {% endfor %}

    </div>
    <div class="container">
        <div >
            
            {% for content in contents %}
            {% if content.chapter_name == cources.chapter_name and content.is_published %}

            {% if content.content_type == 'presentation' %}
            <h2>Презентация по теме: {{ content.chapter_name }}</h2>

            <iframe src="{{ content.file.url }}#toolbar=0" height="800" width="750" frameborder="0"></iframe>
            <hr>
            {% endif %}
            
            {% if content.content_type == 'video' %}
            <h2>Видео по теме: {{ content.chapter_name }}</h2>
            <div class="video-on-page">

                <iframe width="720" height="405" src="{{ content.video }}" frameBorder="0" allow="clipboard-write; autoplay" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
            </div>
            <br>
           
                {% endif %}
                {% endif %}
                {% endfor %}

        </div>
    </div>
</div>


{% endblock content %}

myapp/templates/myapp/eduparts.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->

{% block content %}

<h1 class="test"> {{ cources.title }}</h1>
<div class="container-content">
    <div class="row">
        {% for part in parts %}
        {% if part.edu_area_name == cources.edu_area_name and part.is_published %}
        <div class="col">
            <div class="img-box">
                <img class="img" src="{{ part.image.url }}" class="img-thumbnail" alt="{{ part.title }}">
            </div>
            <div class="description-box">

                <p class="area-description">{{ part.description }}</p>
            </div>
            <a href="{{ part.get_absolute_url }}">
                <div class="d-grid gap-2 col-11 mx-auto">
                    <button class="btn btn-primary" type="button">{{ part.program_name }}</button>
                </div>
            </a>
        </div>
            {% endif %}
            {% endfor %}
    </div>
</div>

{% endblock content %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
<!-- {% load embed_video_tags %} -->
<!-- {% load static %}   -->

{% block content %}


<h1 class="test">Это сайт Академии Тойота предназначенный для самостоятельного изучения учебных материалов, записи на тренинги и сертификацию</h1>
<div>
    <hr>
    <img class="main-img" src="../../../media/images/Toyota-Service-Photo-Lift.jpg" alt="">
</div>
    <hr>
    <div class="content-area-title">
        <h1 class="test"> Разделы сайта </h1>
        
    </div>

<div class="container-content">
    <div class="row">
        {% for section in sections %}
        {% if section.is_published %}
        <div class="col">
            <div class="img-box">
                <img class="img" src="{{ section.image.url }}" class="img-thumbnail" alt="{{ section.section_name }}">
            </div>
            <div class="description-box">
                <p class="area-description">{{ section.description }}</p>

            </div>
            <a href="{% url 'section' section.slug %}">
                <div class="d-grid gap-2 col-11 mx-auto">
                    <button class="btn btn-primary" type="button">{{ section.button_name }}</button>
                </div>
            </a>
        </div>
        {% endif %}
            {%  endfor %}
    </div>
    <hr>
</div>

{% endblock content %}





myapp/templates/myapp/info.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->

{% block content %}

<h1 class="test">Вы находитесь в разделе Информация</h1>
<br>

{% for i in info %}

<div>
    
</div>
<h2>

    {{i.title}}
</h2>

    {{ i.short_description|linebreaks|truncatewords:60 }}


    <a href="{% url 'info_detailes' i.slug %}">

        <div>
            <button type="button" class="btn btn-primary">Читать</button>
        </div>
    </a>
<hr>
{% endfor%}



{% endblock content %}

myapp/templates/myapp/info_details.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->

{% block content %}

<h1 class="test">Вы находитесь в разделе Информация</h1>
<br>

{% for i in info %}

<div>
    
</div>
<h2>

    {{i.title}}
</h2>

    {{ i.content|linebreaks}}



    <a href="{% url 'info' %}">

        <div>
            <button type="button" class="btn btn-primary">Назад</button>
        </div>
    </a>

<hr>
{% endfor%}



{% endblock content %}

myapp/templates/myapp/messages.html
{% if messages %}
  {% for message in messages %}

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>
    
    <div class="alert alert-primary d-flex align-items-center" role="alert">
      <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Info:"><use xlink:href="#info-fill"/></svg>
      <div>
        Все прошло успешно! Вы зарегистрировали сотрудника на предстоящее мероприятие. <br>
        Вы можете внести изменения если это необходимо или нажмите на кнопку "Главная" для переходна на главную страницу
      </div>
    </div>

 {% endfor %}
{% endif %}

myapp/templates/myapp/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-navbar">
      <img class="logo"
  src="../../../media/images/toyota_logo.svg"
  alt="toyota_logo"
  height="87px"
  width="100px" />
      <a class="navbar-brand" href="http://127.0.0.1:8000/">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <div class="left-side-navbar">

            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1:8000/info/">Информация</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1:8000/cert_results/">Cертификаты</a>
            </li>
            {% if request.user.access_rights == 'admin' or request.user.access_rights == 'trainer'%}
            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1:8000/team/">Команда</a>
            </li>
            {% endif %}

          </div>
          

        </ul>

      </div>
    </div>
    <div class="right-side-navbar">
      {% if request.user.access_rights == 'admin' %}
      <li class="nav-item">
        <a class="nav-link" href='{% url "users:register" %}'>Регистрация</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href='{% url "users:profile_search" %}'>Профиль</a>
      </li>
      {% endif %}

      {% if request.user.is_authenticated %}
      <div class="last-word">
        <a class="nav-link" href='{% url "users:logout" %}'>Выйти</a>

      </div>
      <div class="user-name">
        <div class="user-title">
          <h6>Пользователь:</h6>
        </div>
        <div>
          <h6 class="nav-link">
            {{request.user}}
          </h6>

        </div>

      </div>
      <li class="nav-item"> 
      {% endif %}
      </li>


    </div>
  </nav>

myapp/templates/myapp/quiz_start_page.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->

{% block content %}

<h1 class="test"> стартовая страница тестирования </h1>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus libero dolor mollitia tenetur sapiente nihil sint esse, rerum perspiciatis delectus, ullam ex, quidem ad rem voluptate et quibusdam eos enim.</p>

<a href="#">
    <div class="d-grid gap-2 col-11 mx-auto">
        <button class="btn btn-primary" type="button">#</button>
    </div>
</a>


{% endblock content %}

myapp/templates/myapp/success_appointment.html
{% extends 'myapp/base.html' %}

{% block content %}
<h1>Вы успешно записали сотрудника на предстоящее мероприятие!!</h1>

<p><a href="{% url 'index' %}">Вернуться в главное меню.</a></p>
{% endblock %}

myapp/templates/myapp/trainingappform.html
{% extends 'myapp/base.html' %}
<!-- {% load static %}   -->



{% block content %}


<h1 class="test"> {{ cources.title }}</h1>
{% include "myapp/messages.html" %}

<form action="" method="post" >
    {% csrf_token %}
    
    <table class="table-form">
        
        {{ form.as_table }}
        </table>
    <p><button type="submit" class="btn btn-primary">Зарегистрировать</button></p>
</form>

{% endblock content %}